Copy pull request #84 from original repository.
Unicon/edu_edfi_source pull request #1
Opened 2024-07-03 15:20 UTC by maxalmazov

See: https://github.com/edanalytics/edu_edfi_source/pull/84

2024-07-08 18:09 UTC, holdorph requested changes

2024-07-08 18:09 UTC, holdorph commented on models/staging/tpdm/stage/stg_tpdm__educator_preparation_programs.sql
The whitespace formatting on this file does not match the original file.  Please adjust it back to the original file's formatting.

2024-07-09 15:03 UTC, holdorph approved these changes

2024-07-09 15:06 UTC, maxalmazov commented on models/staging/tpdm/stage/stg_tpdm__educator_preparation_programs.sql
Hi @holdorph , I updated format

2024-07-09 15:15 UTC, merged