Debug tpdm models
Unicon/edu_edfi_source pull request #21
Opened 2024-08-12 16:25 UTC by zaharenka

2024-08-12 16:31 UTC, zaharenka commented on dbt_project.yml
> -        +enabled: "{{ var('edu:tpdm:enabled', false) }}"
If we want, we can play with variable in order to have control of materializing whether to include them in dbt run or not. But I don't feel it really needed.

2024-08-12 17:00 UTC, holdorph requested changes

2024-08-12 17:00 UTC, holdorph commented on dbt_project.yml
> -        +enabled: "{{ var('edu:tpdm:enabled', false) }}"
Please remove this change from the PR for now.  I'd like to get the other change from this PR merged, but I'm not sure Erik will agree to this dbt_project.yml change, but the ::personId change is needed for certain.

2024-08-12 17:28 UTC, holdorph commented on dbt_project.yml
> -        +enabled: "{{ var('edu:tpdm:enabled', false) }}"
I did also ask Erik about this though, will update my comment here, if I learn anything that changes the request above to remove this change.

2024-08-13 20:45 UTC, zaharenka commented on dbt_project.yml
> -        +enabled: "{{ var('edu:tpdm:enabled', false) }}"
Left the variable as this. Will try my idea to define +enable in models level, but not for folder level

2024-08-13 20:46 UTC, zaharenka commented on dbt_project.yml
> -        +enabled: "{{ var('edu:tpdm:enabled', false) }}"
If I find solution, I'll produce new PR.

2024-08-13 21:17 UTC, holdorph commented on dbt_project.yml
> -        +enabled: "{{ var('edu:tpdm:enabled', false) }}"
the code that goes into main, therefore the code that goes into the ed analytics PR needs to have this in there, we can just comment out the line locally for now, but that should not be removed for the code that is in main.

2024-08-13 21:29 UTC, holdorph requested changes
Please remove the base_tpdm__evaluation_elements.sql and corresponding stage files.

2024-08-14 11:22 UTC, zaharenka commented on dbt_project.yml
> -        +enabled: "{{ var('edu:tpdm:enabled', false) }}"
Ok, got it. Let's leave the code as it was before - done.

2024-08-14 15:07 UTC, holdorph approved these changes

2024-08-14 15:25 UTC, groybal approved these changes

2024-08-14 15:27 UTC, merged